In [2]:
import numpy as np
data = [ 1, 2, 3, 4, 5,]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [3]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,11, 4)

array([0, 4, 8])

In [6]:
np.zeros(2)

array([0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.linspace(0,5,111)

array([0.        , 0.04545455, 0.09090909, 0.13636364, 0.18181818,
       0.22727273, 0.27272727, 0.31818182, 0.36363636, 0.40909091,
       0.45454545, 0.5       , 0.54545455, 0.59090909, 0.63636364,
       0.68181818, 0.72727273, 0.77272727, 0.81818182, 0.86363636,
       0.90909091, 0.95454545, 1.        , 1.04545455, 1.09090909,
       1.13636364, 1.18181818, 1.22727273, 1.27272727, 1.31818182,
       1.36363636, 1.40909091, 1.45454545, 1.5       , 1.54545455,
       1.59090909, 1.63636364, 1.68181818, 1.72727273, 1.77272727,
       1.81818182, 1.86363636, 1.90909091, 1.95454545, 2.        ,
       2.04545455, 2.09090909, 2.13636364, 2.18181818, 2.22727273,
       2.27272727, 2.31818182, 2.36363636, 2.40909091, 2.45454545,
       2.5       , 2.54545455, 2.59090909, 2.63636364, 2.68181818,
       2.72727273, 2.77272727, 2.81818182, 2.86363636, 2.90909091,
       2.95454545, 3.        , 3.04545455, 3.09090909, 3.13636364,
       3.18181818, 3.22727273, 3.27272727, 3.31818182, 3.36363

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand(5)

array([0.84142725, 0.05520582, 0.55152596, 0.51702743, 0.30131556])

In [12]:
np.random.rand(5,5)

array([[0.65475789, 0.78705525, 0.79870801, 0.02138816, 0.12563943],
       [0.08500003, 0.20790795, 0.70054419, 0.64074197, 0.7707532 ],
       [0.41226281, 0.57850182, 0.92548583, 0.73062222, 0.92805034],
       [0.21021924, 0.34496297, 0.04181839, 0.50995871, 0.86191051],
       [0.54986436, 0.25012518, 0.80538902, 0.24606088, 0.11632607]])

In [13]:
np.random.randn(2)

array([-1.87105322,  1.60080362])

In [14]:
np.random.randn(2,2)

array([[ 1.27990619,  0.00896303],
       [-1.33962187,  0.11463624]])

In [15]:
np.random.randint(1,100,45)

array([71,  2, 31, 81, 74, 75, 40, 67, 62, 43, 46, 87,  4, 86, 49, 88, 68,
       54, 42, 45, 18, 96, 33, 23, 91, 59, 52, 41, 56, 99, 28, 57, 99, 58,
       24, 94, 59, 23, 76, 69, 15, 89,  9, 18, 20])

In [16]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
randarr = np.random.randint(0,50,10)
randarr

array([ 4, 11, 31,  7, 48, 49,  9,  7, 11, 49])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
randarr

array([ 4, 11, 31,  7, 48, 49,  9,  7, 11, 49])

In [20]:
randarr.max()

49

In [21]:
randarr.min()

4

In [22]:
randarr.argmax()

5

In [23]:
randarr.argmin()

0

In [24]:
ar = arr.reshape(5,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ar.shape

(5, 5)

In [26]:
ar.dtype

dtype('int64')