In [1]:
import numpy as np
data = [ 1, 2, 3, 4, 5,]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,11, 4)

array([0, 4, 8])

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(5)

array([0.70848867, 0.92007515, 0.42562557, 0.12562258, 0.20467562])

In [11]:
np.random.rand(5,5)

array([[0.75410626, 0.71053807, 0.20867819, 0.7918905 , 0.90389145],
       [0.80210451, 0.39920915, 0.94476236, 0.48734756, 0.66196207],
       [0.816842  , 0.60841679, 0.75407991, 0.02233651, 0.04989766],
       [0.03505776, 0.65282995, 0.80968363, 0.6474328 , 0.61410276],
       [0.11251913, 0.27606135, 0.58838002, 0.54435041, 0.46350087]])

In [12]:
np.random.randn(2)

array([-1.03679126,  0.44559935])

In [13]:
np.random.randn(2,2)

array([[ 2.01399592, -0.27884692],
       [ 0.03662157, -0.78441642]])

In [14]:
np.random.randint(1,100,45)

array([84, 84, 57, 99, 20, 69, 20, 43, 75, 69, 30, 85, 90, 28,  5, 78, 93,
       99, 99, 96, 72,  7, 94, 75, 16, 77, 33, 92, 19, 13, 19, 71, 14, 28,
       42, 49, 66, 77, 24, 37, 84, 62, 19, 79, 18])

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
randarr = np.random.randint(0,50,10)
randarr

array([18, 32, 35, 48, 48,  3, 20, 16,  0, 43])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
randarr

array([18, 32, 35, 48, 48,  3, 20, 16,  0, 43])

In [19]:
randarr.max()

48

In [20]:
randarr.min()

0

In [21]:
randarr.argmax()

3

In [22]:
randarr.argmin()

8

In [23]:
ar = arr.reshape(5,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ar.shape

(5, 5)

In [25]:
ar.dtype

dtype('int64')