In [7]:
import numpy as np
data = [ 1, 2, 3, 4, 5,]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11, 4)

array([0, 4, 8])

In [15]:
np.zeros(2)

array([0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.random.rand(5)

array([0.38848028, 0.6033317 , 0.36545866, 0.67195729, 0.69644614])

In [35]:
np.random.rand(5,5)

array([[0.05249539, 0.22400131, 0.38488676, 0.35234645, 0.64245417],
       [0.08049498, 0.19032723, 0.97455017, 0.82499297, 0.84725886],
       [0.25257727, 0.92201183, 0.63424716, 0.80532365, 0.52105646],
       [0.94000797, 0.68308553, 0.44985502, 0.52637105, 0.2810602 ],
       [0.97337008, 0.47521764, 0.86887681, 0.99817146, 0.18144724]])

In [36]:
np.random.randn(2)

array([-0.78418954,  0.46463526])

In [37]:
np.random.randn(2,2)

array([[ 0.46754372, -0.22581734],
       [ 1.20484637, -0.43564624]])

In [43]:
np.random.randint(1,100,45)

array([81, 54, 60, 64, 93, 88, 32, 66, 74, 29, 66, 72, 64, 19, 63, 70, 42,
       68, 48, 80, 16, 85, 99, 24, 59, 67, 48, 47, 32,  5, 15, 85, 24, 69,
       34, 48, 90,  9, 26, 22, 38, 23, 21, 38, 54])

In [45]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
randarr = np.random.randint(0,50,10)
randarr

array([47, 28, 43, 42, 25,  6, 11,  8, 12, 48])

In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
randarr

array([47, 28, 43, 42, 25,  6, 11,  8, 12, 48])

In [54]:
randarr.max()

48

In [55]:
randarr.min()

6

In [56]:
randarr.argmax()

9

In [57]:
randarr.argmin()

5

In [59]:
ar = arr.reshape(5,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
ar.shape

(5, 5)

In [61]:
ar.dtype

dtype('int64')