In [74]:
import numpy as np

In [75]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr[9]

9

In [77]:
arr[1:5]

array([1, 2, 3, 4])

In [78]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [79]:
arr[7:]

array([7, 8, 9])

In [80]:
arr[0:7] = np.random.randint(1,100,7)
arr

array([59, 13, 15, 52, 85, 54, 57,  7,  8,  9])

In [81]:
slice_of_arr = arr[0:4]
slice_of_arr

array([59, 13, 15, 52])

In [82]:
arr

array([59, 13, 15, 52, 85, 54, 57,  7,  8,  9])

In [83]:
#Using copy will make a new variable with it's own value and won't affect the original variable,
arr_copy = arr.copy()

In [84]:
# Select all and make it 230
arr_copy[:] = 230
arr_copy

array([230, 230, 230, 230, 230, 230, 230, 230, 230, 230])

In [85]:
arr

array([59, 13, 15, 52, 85, 54, 57,  7,  8,  9])

In [86]:
# Creating a 2D Array

arr_2d = np.array([[4,2,1],[23,34,45],[78,90,65]])
arr_2d

array([[ 4,  2,  1],
       [23, 34, 45],
       [78, 90, 65]])

In [87]:
# Row ans column
arr_2d[1][2]

45

In [88]:
arr_2d[2,1]

90

In [89]:
#Everything befor 2nd row and Everything after 1st Column
arr_2d[:2,1:]

array([[ 2,  1],
       [34, 45]])

In [90]:
new_arr = np.arange(1,15)
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
# This will print Boolean Values
bool_arr = new_arr > 8
bool_arr

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True])

In [92]:
new_arr[bool_arr]

array([ 9, 10, 11, 12, 13, 14])

In [93]:
# You can also try like this and this is more beneficial.
new_arr[new_arr>10] 

array([11, 12, 13, 14])

In [101]:
arr_2d = np.arange(8).reshape(4,2)
arr_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [104]:
arr_2d = np.arange(25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
arr_2d[1:3,3:5]

array([[ 8,  9],
       [13, 14]])