In [13]:
import numpy as np
arr = np.random.randint(1,100,12)
arr

array([24, 71,  5, 79, 47, 69, 95, 20, 18,  3, 81, 33])

In [14]:
arr + arr

array([ 48, 142,  10, 158,  94, 138, 190,  40,  36,   6, 162,  66])

In [15]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr * arr

array([ 576, 5041,   25, 6241, 2209, 4761, 9025,  400,  324,    9, 6561,
       1089])

In [17]:
arr + 100

array([124, 171, 105, 179, 147, 169, 195, 120, 118, 103, 181, 133])

In [18]:
arr - 55

array([-31,  16, -50,  24,  -8,  14,  40, -35, -37, -52,  26, -22])

In [26]:
arr * 5 / arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [27]:
arr ** 2

array([ 576, 5041,   25, 6241, 2209, 4761, 9025,  400,  324,    9, 6561,
       1089])

In [28]:
1/arr

array([0.04166667, 0.01408451, 0.2       , 0.01265823, 0.0212766 ,
       0.01449275, 0.01052632, 0.05      , 0.05555556, 0.33333333,
       0.01234568, 0.03030303])

In [29]:
np.sqrt(arr)

array([4.89897949, 8.42614977, 2.23606798, 8.88819442, 6.8556546 ,
       8.30662386, 9.74679434, 4.47213595, 4.24264069, 1.73205081,
       9.        , 5.74456265])

In [30]:
#Calculating the exponential

np.exp(arr)

array([2.64891221e+10, 6.83767123e+30, 1.48413159e+02, 2.03828107e+34,
       2.58131289e+20, 9.25378173e+29, 1.81123908e+41, 4.85165195e+08,
       6.56599691e+07, 2.00855369e+01, 1.50609731e+35, 2.14643580e+14])

In [31]:
np.max(arr)
# OR
arr.max()

95

In [32]:
np.sin(arr)

array([-0.90557836,  0.95105465, -0.95892427, -0.44411267,  0.12357312,
       -0.11478481,  0.68326171,  0.91294525, -0.75098725,  0.14112001,
       -0.62988799,  0.99991186])

In [33]:
np.log(arr)

array([3.17805383, 4.26267988, 1.60943791, 4.36944785, 3.8501476 ,
       4.2341065 , 4.55387689, 2.99573227, 2.89037176, 1.09861229,
       4.39444915, 3.49650756])